### ISSUE TITLE
Email Report plugin version 1.1.11 had issue with not sending email on azure devops pipeline

### ISSUE THREAD

**Issue by padmavathidasaradhan** [microsoft/azure-devops-engineering-extensions#107]
Hi,

Starting: Email Test Results
==============================================================================
Task         : Email Report
Description  : Send rich email report for test results and for tasks in this stage
Version      : 1.1.11
Author       : Microsoft Corporation
Help         : Sets 'EmailReportTask.EmailSent' variable to true if it sent email successfully. [Learn More](https://marketplace.visualstudio.com/items?itemName=epsteam.EmailReportExtension)
==============================================================================

I have configured the Email report v 1.1.11 but  im getting the below error .MailError: Error: Error upgrading connection with STARTTLS: 554 5.7.3 Unable to initialize security subsystem
 MailError: Error: Error upgrading connection with STARTTLS: 554 5.7.3 Unable to initialize security subsystem
    at ReportError (/__w/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.11/exceptions/ReportError.js:7:9)
    at MailError (/__w/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.11/exceptions/MailError.js:7:9)
    at EmailSender.<anonymous> (/__w/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.11/EmailSender.js:68:23)
    at throw (native)
    at rejected (/__w/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.11/EmailSender.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:109:7)
MailError: Error: Error upgrading connection with STARTTLS: 554 5.7.3 Unable to initialize security subsystem
 MailError: Error: Error upgrading connection with STARTTLS: 554 5.7.3 Unable to initialize security subsystem
    at ReportError (/__w/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.11/exceptions/ReportError.js:7:9)
    at MailError (/__w/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.11/exceptions/MailError.js:7:9)
(node:1598) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MailError: Error: Error upgrading connection with STARTTLS: 554 5.7.3 Unable to initialize security subsystem
    at EmailSender.<anonymous> (/__w/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.11/EmailSender.js:68:23)
    at throw (native)
    at rejected (/__w/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.11/EmailSender.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Task Processing Complete.
##[debug]Handler exit code: 0

Could you please check on this?

Thanks,
Padma.

**Comment by madkoo** [comment]
Hi @padmavathidasaradhan, since you reporthed the error there have been new releases published. Try again with the newer version. 

if problem persists let us know. I will close the issue for now.
