### ISSUE TITLE
Certificate Error in Email Report Extension

### ISSUE THREAD

**Issue by kgidewall** [microsoft/azure-devops-engineering-extensions#41]
We are getting an error related to a certificate when trying to run Email Report Extension. It has always worked for us in the past, but this started happening recently. I am not sure how a certificate is coming into play here. I have tried to create a new PAT and Service Connection to see if that might be the problem, but we still see the same error. I'm wondering if the certificate is something internal? Here is a copy of the log output. Please advise:

2020-06-01T23:51:28.6785027Z ##[section]Starting: Send Email Report
2020-06-01T23:51:28.6898988Z ==============================================================================
2020-06-01T23:51:28.6899306Z Task         : Email Report
2020-06-01T23:51:28.6899628Z Description  : Send rich email report for test results and for tasks in this stage
2020-06-01T23:51:28.6899920Z Version      : 1.1.8
2020-06-01T23:51:28.6900155Z Author       : Microsoft Corporation
2020-06-01T23:51:28.6900682Z Help         : Sets 'EmailReportTask.EmailSent' variable to true if it sent email successfully. [Learn More](https://marketplace.visualstudio.com/items?itemName=epsteam.EmailReportExtension)
2020-06-01T23:51:28.6901258Z ==============================================================================
2020-06-01T23:51:29.3894546Z Node Version: v6.17.1
2020-06-01T23:51:29.4292429Z Fetching data for email report
2020-06-01T23:51:29.8096165Z Fetched test owners data
2020-06-01T23:51:30.0266537Z Getting Test summary data for test run - Tests results for OC.Inventory.Tests.ProdAll 060120_045014 1 in OC.Inventory.Prod.DM3
2020-06-01T23:51:30.1960994Z Fetching last release by completed environment id - 7006548 and branch id refs/heads/master
2020-06-01T23:51:30.7998530Z Considering one of [1443761,1443748,1443702,1443676,1443651,1443632,1443621,1443596,1443568,1443539,1443523,1443505,1443480,1443466,1443451,1443433,1443419,1443397,1443384,1443366,1443350,1443314,1443296,1443278,1443263,1443239,1443199,1443084,1442978,1442896,1442878,1442854,1442817,1442782,1442731,1442696,1442610,1442537,1442501,1442401,1442354,1442312,1442275,1442231,1442201,1442176,1442152,1442138,1442131,1442122] as previous completed release for 1443793
2020-06-01T23:51:30.9276268Z Getting changes between releases 1443793 & 1443761
2020-06-01T23:51:30.9280435Z Fetching changes between releases - 1443761 & 1443793
2020-06-01T23:51:31.2479892Z No changes found between releases - 1443761 & 1443793
2020-06-01T23:51:31.2480297Z Fetched release data
2020-06-01T23:51:31.2711431Z Created report view model
2020-06-01T23:51:31.2711798Z Creating report message
2020-06-01T23:51:31.2712141Z CurrentDir: E:\agent_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\htmlreport
2020-06-01T23:51:31.2712718Z Loading Email Template: E:\agent_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\htmlreport\EmailTemplate.xslt
2020-06-01T23:51:31.2713171Z Creating summary group viewmodel for 1
2020-06-01T23:51:31.3737841Z computing email addresses for to section
2020-06-01T23:51:31.3753864Z computing email addresses for Cc section
2020-06-01T23:51:31.3754289Z Using SmtpHost URL: smtphost.redmond.corp.microsoft.com
2020-06-01T23:51:31.3754752Z Parsed Url: smtp://smtphost.redmond.corp.microsoft.com
2020-06-01T23:51:31.3759748Z Host: smtphost.redmond.corp.microsoft.com
2020-06-01T23:51:31.3760074Z HostName: smtphost.redmond.corp.microsoft.com
2020-06-01T23:51:31.3760281Z Port: null
2020-06-01T23:51:31.3760465Z Protocol: smtp:
2020-06-01T23:51:31.3760746Z Using HostName: smtphost.redmond.corp.microsoft.com and port: 587
2020-06-01T23:51:31.4302523Z MailError: Error: unable to verify the first certificate
2020-06-01T23:51:31.4302972Z  MailError: Error: unable to verify the first certificate
2020-06-01T23:51:31.4303487Z     at ReportError (E:\agent_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\ReportError.js:6:9)
2020-06-01T23:51:31.4304136Z     at MailError (E:\agent_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\MailError.js:6:9)
2020-06-01T23:51:31.4304780Z     at EmailSender.<anonymous> (E:\agent_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:66:23)
2020-06-01T23:51:31.4305186Z     at throw (native)
2020-06-01T23:51:31.4305585Z     at rejected (E:\agent_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:5:65)
2020-06-01T23:51:31.4306048Z     at process._tickCallback (internal/process/next_tick.js:109:7)
2020-06-01T23:51:31.4306406Z MailError: Error: unable to verify the first certificate
2020-06-01T23:51:31.4307762Z  MailError: Error: unable to verify the first certificate
2020-06-01T23:51:31.4308237Z     at ReportError (E:\agent_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\ReportError.js:6:9)
2020-06-01T23:51:31.4308887Z     at MailError (E:\agent_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\MailError.js:6:9)
2020-06-01T23:51:31.4309624Z     at EmailSender.<anonymous> (E:\agent_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:66:23)
2020-06-01T23:51:31.4310034Z     at throw (native)
2020-06-01T23:51:31.4310399Z     at rejected (E:\agent_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:5:65)
2020-06-01T23:51:31.4310855Z     at process._tickCallback (internal/process/next_tick.js:109:7)
2020-06-01T23:51:31.4311110Z Task Processing Complete.
2020-06-01T23:51:31.4402798Z (node:49100) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MailError: Error: unable to verify the first certificate
2020-06-01T23:51:31.4525880Z ##[section]Finishing: Send Email Report

**Comment by chetanmsft** [comment]
We started having the exact same issue from past 3 months. @kgidewall did you guys find any workarounds ?

**Comment by chetanmsft** [comment]
@saikrishnav @LeahSchwartz  Can one of you please help here ?
