### ISSUE TITLE
Fails with HTTP 401 - Unauthorized

### ISSUE THREAD

**Issue by harshgandhi18** [microsoft/azure-devops-engineering-extensions#50]
Hi, I am using this extension for sending Test results from AzureDevOps build pipeline. I am facing an issue using the tool. This could be more a question than an issue.

**Problem#1**
I added SMTP in "Service Connection - Generic". My SMTP is configured for Anonumous Auth. I left the Service Connection creds to empty. It failed with following message.

_401 - Unauthorized: Access is denied due to invalid credentials._

Do you know if the extension works with anonymous auth on SMTP?

**Problem#2**
I tried configure SMTP with Authentication and updated service connection details to use Creds provided. It still keeps failing with the same message

_401 - Unauthorized: Access is denied due to invalid credentials._

Is there a way to look at detailed logs whether it fails on SMTP or on the extension itself? 

From the Stacktrace below, it looks like it fails on extension itself. Is there a way to see detailed logs to figure what is wrong? 

Stacktrace:

Node Version: v6.10.3
Fetching data for email report
Retry <GetPipeline>: 1 : Error: 
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  
    at RestClient.<anonymous> (d:\b\4\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\node_modules\typed-rest-client\RestClient.js:202:31)
    at next (native)
    at fulfilled (d:\b\4\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\node_modules\typed-rest-client\RestClient.js:6:58)
    at process._tickCallback (internal/process/next_tick.js:109:7) statusCode: 401 }
##[section]Finishing: Send Email Report Always

**Comment by xiuzhen1103** [comment]
How do you add added SMTP in "Service Connection - Generic"? @harshgandhi18
