### ISSUE TITLE
Send Email failed due to Invalid log in error. ("SMTP Credentials" set to "O365 SMTPHost Connection for FPS")

### ISSUE THREAD

**Issue by kyongk** [microsoft/azure-devops-engineering-extensions#64]
"SMTP Credentials" in "Email Report" task set to "O365 SMTPHost Connection for FPS"

**Error message**
Using SmtpHost URL: smtp.office365.com:587
Parsed Url: smtp://smtp.office365.com:587
Host: smtp.office365.com:587
HostName: smtp.office365.com
Port: 587
Protocol: smtp:
Using HostName: smtp.office365.com and port: 587
MailError: Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [SG2PR02CA0073.apcprd02.prod.outlook.com]
 MailError: Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [SG2PR02CA0073.apcprd02.prod.outlook.com]
    at ReportError (D:\a\_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\ReportError.js:6:9)
    at MailError (D:\a\_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\MailError.js:6:9)
    at EmailSender.<anonymous> (D:\a\_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:66:23)
    at throw (native)
    at rejected (D:\a\_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:109:7)
MailError: Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [SG2PR02CA0073.apcprd02.prod.outlook.com]
 MailError: Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [SG2PR02CA0073.apcprd02.prod.outlook.com]
    at ReportError (D:\a\_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\ReportError.js:6:9)
    at MailError (D:\a\_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\MailError.js:6:9)
    at EmailSender.<anonymous> (D:\a\_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:66:23)
    at throw (native)
    at rejected (D:\a\_work\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Task Processing Complete.
(node:3436) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MailError: Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [SG2PR02CA0073.apcprd02.prod.outlook.com]

**Comment by kyongk** [comment]
I have no idea what fixed the issue but the task started sending emails properly since around 1 pm in PST today (1/6/2022)
