### ISSUE TITLE
MailError: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by tle15** [microsoft/azure-devops-engineering-extensions#67]
Hi,

I have been using this extension for my pipeline, and I have been facing the following error since 01/29/2022. Could you give me any pointer on how to resolve the error?

Starting: EmailReport 
Task : Email Report 
Description : Send rich email report for test results and for tasks in this stage 
Version : 1.1.8 
Author : Microsoft Corporation 
Help : Sets 'EmailReportTask.EmailSent' variable to true if it sent email successfully. [Learn More]([https://marketplace.visualstudio.com/items?itemName=epsteam.EmailReportExtension](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Depsteam.EmailReportExtension&data=04%7C01%7Ctienle%40microsoft.com%7C60141223d91b475ed7b608d9eaaa3b98%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637798839251612327%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BV1FFpJtGp076fMg4RKrWkUHzNOagntNiscmx0mwvM8%3D&reserved=0)) 

Node Version: v6.17.1 
Fetching data for email report 
Fetched test owners data 
No changes found for pipelineId - 13603 
Fetched release data 
Created report view model 
Creating report message 
CurrentDir: D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\htmlreport 
Loading Email Template: D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\htmlreport\EmailTemplate.xslt 
Total Test count is 0. Setting outcome percentage to 0 
Creating summary group viewmodel for 1 
computing email addresses for to section 
No changeset owner mail addresses 
computing email addresses for Cc section 
Using SmtpHost URL: smtp.live.com 
Parsed Url: smtp://smtp.live.com 
Host: smtp.live.com 
HostName: smtp.live.com 
Port: null 
Protocol: smtp: 
Using HostName: smtp.live.com and port: 587 
MailError: Error: connect ETIMEDOUT 204.79.197.212:587 
MailError: Error: connect ETIMEDOUT 204.79.197.212:587 
MailError: Error: connect ETIMEDOUT 204.79.197.212:587 
at ReportError (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\ReportError.js:6:9) 
at MailError (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\MailError.js:6:9) 
at EmailSender.<anonymous> (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:66:23) 
at throw (native) 
at rejected (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:5:65) 
at process._tickCallback (internal/process/next_tick.js:109:7) 
Task Processing Complete. 
MailError: Error: connect ETIMEDOUT 204.79.197.212:587 
at ReportError (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\ReportError.js:6:9) 
at MailError (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\MailError.js:6:9) 
at EmailSender.<anonymous> (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:66:23) 
at throw (native) 
at rejected (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:5:65) 
at process._tickCallback (internal/process/next_tick.js:109:7) 
(node:5780) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MailError: Error: connect ETIMEDOUT 204.79.197.212:587

**Comment by Madhavivsp** [comment]
We are also getting same issue for our server URL "https://smtphost.redmond.corp.microsoft.com" in our validation pipeline for Email Report Task, is there any update on this thread?
 Using HostName: smtphost.redmond.corp.microsoft.com and port: 587
2022-06-28T23:57:35.9133542Z MailError: Error: connect ETIMEDOUT xx.xxx.xxx.xx:587
2022-06-28T23:57:35.9134363Z  MailError: Error: connect ETIMEDOUT

**Comment by sathishmugithe** [comment]
We are also facing the same issue, where we have configured SendGrid SMTP Host URL and Credentials in "Send Email Report Always" task Azure Pipeline. is there any update on this?
