### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/htmlreport\EmailTemplate.xslt

### ISSUE THREAD

**Issue by suneelsingh** [microsoft/azure-devops-engineering-extensions#70]
Getting below error on ubuntu machine. Can you help on this?

`{ Error: ENOENT: no such file or directory, open '/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/htmlreport\EmailTemplate.xslt'
2022-04-27T14:12:18.7692107Z     at Error (native)
2022-04-27T14:12:18.7692929Z     at Object.fs.openSync (fs.js:642:18)
2022-04-27T14:12:18.7693760Z     at Object.fs.readFileSync (fs.js:510:33)
2022-04-27T14:12:18.7695437Z     at HTMLReportCreator.createHtmlReport (/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/htmlreport/HTMLReportCreator.js:19:27)
2022-04-27T14:12:18.7697274Z     at ReportManager.<anonymous> (/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/ReportManager.js:32:64)
2022-04-27T14:12:18.7698273Z     at next (native)
2022-04-27T14:12:18.7699577Z     at fulfilled (/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/ReportManager.js:4:58)
2022-04-27T14:12:18.7700652Z     at process._tickCallback (internal/process/next_tick.js:109:7)
2022-04-27T14:12:18.7701637Z   errno: -2,
2022-04-27T14:12:18.7702482Z   code: 'ENOENT',
2022-04-27T14:12:18.7703278Z   syscall: 'open',
2022-04-27T14:12:18.7704579Z   path: '/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/htmlreport\\EmailTemplate.xslt' }
2022-04-27T14:12:18.7706747Z (node:6865) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/htmlreport\EmailTemplate.xslt'
2022-04-27T14:12:18.7707962Z Total Test count is 0. Setting outcome percentage to 0
2022-04-27T14:12:18.7708555Z Creating summary group viewmodel for 1
2022-04-27T14:12:18.7710285Z { Error: ENOENT: no such file or directory, open '/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/htmlreport\EmailTemplate.xslt'
2022-04-27T14:12:18.7711201Z     at Error (native)
2022-04-27T14:12:18.7711734Z     at Object.fs.openSync (fs.js:642:18)
2022-04-27T14:12:18.7712369Z     at Object.fs.readFileSync (fs.js:510:33)
2022-04-27T14:12:18.7713767Z     at HTMLReportCreator.createHtmlReport (/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/htmlreport/HTMLReportCreator.js:19:27)
2022-04-27T14:12:18.7715974Z     at ReportManager.<anonymous> (/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/ReportManager.js:32:64)
2022-04-27T14:12:18.7716786Z     at next (native)
2022-04-27T14:12:18.7717891Z     at fulfilled (/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/ReportManager.js:4:58)
2022-04-27T14:12:18.7718788Z     at process._tickCallback (internal/process/next_tick.js:109:7)
2022-04-27T14:12:18.7719910Z   errno: -2,
2022-04-27T14:12:18.7720530Z   code: 'ENOENT',
2022-04-27T14:12:18.7721123Z   syscall: 'open',
2022-04-27T14:12:18.7722149Z   path: '/mnt/vss/_work/_tasks/EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105/1.1.8/htmlreport\\EmailTemplate.xslt' }
2022-04-27T14:12:18.7722913Z Task Processing Complete.`

**Comment by rakuju87** [comment]
@suneelsingh Were you able to fix it? I am trying on the macOS agent and getting the same error. There is an option "https://marketplace.visualstudio.com/items?itemName=calrom-jtejero.CalromEmailReportExtension". have you tried it?

**Comment by thegrandpoobah** [comment]
still hitting this with v2 as well.. the issue i think is that you are using windows path separators on line 15 of the file in question (https://github.com/microsoft/azure-devops-engineering-extensions/blob/1a878db055191ba53326f4db7c3413f22c2238f7/Extensions/emailReportTask/Tasks/emailReportTask/emailReportTaskV2/htmlreport/HTMLReportCreator.ts#L15). obviously wont work on unix based oses...

would hope ms would fix it...

**Comment by Hiaslafson** [comment]
Any updates on this? having the same issue...
