### ISSUE TITLE
Email Report Extension task throwing error in SMTP login. 

### ISSUE THREAD

**Issue by Ramya-198812** [microsoft/azure-devops-engineering-extensions#87]
Hi, As per our requirement we need to send an email once the Functional testing executed via pipeline and we also need to send the test results in email. So we have installed the "Email Report Extension " from marketplace and configured the SMPT service connection as well. But while executing the pipeline it throwing the Timeout Error.  

Please help us to fix this issue. 

Attaching the logs for your reference : 

2023-03-30T03:17:04.4805508Z ##[section]Starting: Send Email Report Always
2023-03-30T03:17:04.4908917Z ==============================================================================
2023-03-30T03:17:04.4909033Z Task         : Email Report
2023-03-30T03:17:04.4909093Z Description  : Send rich email report for test results and for tasks in this stage
2023-03-30T03:17:04.4909201Z Version      : 1.1.8
2023-03-30T03:17:04.4909264Z Author       : Microsoft Corporation
2023-03-30T03:17:04.4909926Z Help         : Sets 'EmailReportTask.EmailSent' variable to true if it sent email successfully. [Learn More](https://marketplace.visualstudio.com/items?itemName=epsteam.EmailReportExtension)
2023-03-30T03:17:04.4910116Z ==============================================================================
2023-03-30T03:17:05.5685422Z Node Version: v6.17.1
2023-03-30T03:17:05.6872442Z Fetching data for email report
2023-03-30T03:17:06.1702441Z Fetched test owners data
2023-03-30T03:17:06.2966581Z Fetching last release by completed environment id - 15239 and branch id refs/heads/SubscriptionKeyms
2023-03-30T03:17:06.4052709Z Unable to fetch last completed release for release definition:40 and environmentid: 195
2023-03-30T03:17:06.4053229Z Unable to find any last completed release
2023-03-30T03:17:06.4053565Z Fetched release data
2023-03-30T03:17:06.8829668Z Getting Test summary data for test run - CampaignManagement-TestSuite
2023-03-30T03:17:07.0098513Z Created report view model
2023-03-30T03:17:07.0107148Z Creating report message
2023-03-30T03:17:07.0108203Z CurrentDir: D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\htmlreport
2023-03-30T03:17:07.0108731Z Loading Email Template: D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\htmlreport\EmailTemplate.xslt
2023-03-30T03:17:07.0109068Z Creating summary group viewmodel for 1
2023-03-30T03:17:07.1211182Z computing email addresses for to section
2023-03-30T03:17:07.1232869Z computing email addresses for Cc section
2023-03-30T03:17:07.1233336Z Using SmtpHost URL: smtp.live.com
2023-03-30T03:17:07.1233629Z Parsed Url: smtp://smtp.live.com
2023-03-30T03:17:07.1233891Z Host: smtp.live.com
2023-03-30T03:17:07.1234140Z HostName: smtp.live.com
2023-03-30T03:17:07.1234365Z Port: null
2023-03-30T03:17:07.1234594Z Protocol: smtp:
2023-03-30T03:17:07.1234839Z Using HostName: smtp.live.com and port: 587
2023-03-30T03:17:28.2684104Z MailError: Error: connect ETIMEDOUT 204.79.197.212:587
2023-03-30T03:17:28.2684401Z MailError: Error: connect ETIMEDOUT 204.79.197.212:587
2023-03-30T03:17:28.2684832Z  MailError: Error: connect ETIMEDOUT 204.79.197.212:587
2023-03-30T03:17:28.2685019Z  MailError: Error: connect ETIMEDOUT 204.79.197.212:587
2023-03-30T03:17:28.2685995Z     at ReportError (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\ReportError.js:6:9)
2023-03-30T03:17:28.2686401Z     at ReportError (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\ReportError.js:6:9)
2023-03-30T03:17:28.2686958Z     at MailError (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\MailError.js:6:9)
2023-03-30T03:17:28.2687381Z     at MailError (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\exceptions\MailError.js:6:9)
2023-03-30T03:17:28.2687926Z     at EmailSender.<anonymous> (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:66:23)
2023-03-30T03:17:28.2688332Z     at EmailSender.<anonymous> (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:66:23)
2023-03-30T03:17:28.2688675Z     at throw (native)
2023-03-30T03:17:28.2688802Z     at throw (native)
2023-03-30T03:17:28.2689255Z     at rejected (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:5:65)
2023-03-30T03:17:28.2689618Z     at rejected (D:\a\_tasks\EmailReport_36fd41b1-8024-4ce9-a5a0-53c3e54ed105\1.1.8\EmailSender.js:5:65)
2023-03-30T03:17:28.2689999Z     at process._tickCallback (internal/process/next_tick.js:109:7)
2023-03-30T03:17:28.2691568Z     at process._tickCallback (internal/process/next_tick.js:109:7)
2023-03-30T03:17:28.2692170Z Task Processing Complete.
2023-03-30T03:17:28.2700066Z (node:3380) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MailError: Error: connect ETIMEDOUT 204.79.197.212:587
2023-03-30T03:17:28.2780609Z ##[section]Finishing: Send Email Report Always

**Comment by Riisko** [comment]
I am having the same issue, I get an email as the person who ran the pipeline but people who are in CC or Recipient don't.
